### ISSUE TITLE
Unable to launch browser

### ISSUE THREAD

**Issue by testuser-23** [paulallen87/chaturbate-overlay-app#2]
Headless chrome browser is not launching properly, even if a manual install of your browser is completed. This is stopped the app from working.

**Comment by testuser-23** [comment]
@paulallen87

**Comment by paulallen87** [comment]
Any chance you could attach the logs? Also are you starting the app from the docker file, or manually?

**Comment by testuser-23** [comment]
I'll grab you logs tomorrow but to add info here(honestly I didn't expect a
reply so thanks for that!) manually calling it from a command line is where
it's failing. However if I do start it from the docker image you left it
as, it runs great.

**Comment by testuser-23** [comment]
Fixed it. Had to manually go through and install the dependencies as well as the dev dependencies. Looking forward to playing around with this though, thanks for your work.
